name: 'Gitbook-Master'

on:
  push:
    branches:
      - master

jobs:
  build:
    name: publish gitbook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yanhuqing666/gitbook-action@1.2.5 # https://github.com/ZanderZhao/gitbook-action/releases 
        with:
          token: ${{ secrets.PUBLISH_TOKEN }}
          time_zone: Asia/Shanghai   # set time zone
          source_branch: master             # clone source master 
          publish_push_force: true
          publish_remove_last_build: false
          gitbook_pdf: true
          gitbook_pdf_dir: /
          gitbook_pdf_name: dble-manual
          #font_install: sudo apt-get install fonts-noto-cjk ttf-mscorefonts-installer
          #prepare_install: bash chj-fonts.sh #sudo add-apt-repository universe && sudo apt update && sudo apt-get install calibre fonts-arphic-gbsn00lp
