name: 'Gitbook-Develop'

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: publish gitbook 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yanhuqing666/gitbook-action@1.2.5
        with:                                # Just example, click above, use latest please
          token: ${{ secrets.PUBLISH_TOKEN }}
          time_zone: Asia/Shanghai   # set time zone
          source_branch: develop             # clone source master
          publish_push_force: true
          publish_dir: /history/develop/
          gitbook_pdf: true
          gitbook_pdf_dir: /
          gitbook_pdf_name: dble-manual
