name: 'Gitbook-Master'

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v4
 
    - name: Gitbook Action
      uses: zanderzhao/gitbook-action@v1.2.4 # https://github.com/ZanderZhao/gitbook-action/releases 
      with:                                # Just example, click above, use latest please 
        token: ${{ secrets.PUBLISH_TOKEN }}
        time_zone: Asia/Shanghai   # set time zone
        source_branch: master             # clone source master 
        publish_push_force: true
        publish_remove_last_build: false
        gitbook_pdf: true
        gitbook_pdf_dir: /
        gitbook_pdf_name: dble-manual
        font_install: sudo apt-get install fonts-noto-cjk ttf-mscorefonts-installer
        prepare_install: sudo add-apt-repository universe && sudo apt update && sudo apt-get install calibre fonts-arphic-gbsn00lp
